# Dockerfile
# Building for production

FROM elixir:alpine as build

RUN mkdir -p /opt/app

COPY . /opt/app
WORKDIR /opt/app

ENV MIX_ENV=prod

RUN apk --no-cache --update add \
  g++ \
  gcc \
  git \
  libc-dev \
  make \
  nodejs \
  nodejs-npm \
  python

RUN cd /opt/app && \
  mix local.hex --force && \
  mix local.rebar --force && \
  mix deps.get && \
  mix deps.compile --all

RUN npm install npm -g --no-progress && \
  cd /opt/app/assets && \
  npm ci && \
  NODE_ENV=production npm run build

RUN mix release

# Dockerfile
# Runing in production

FROM elixir:alpine as release

RUN apk add --no-cache bash openssl

RUN mkdir -p /opt/app
RUN chown nobody:nobody /opt/app

USER nobody:nobody

COPY --from=build --chown=nobody:nobody /opt/app/_build/prod/rel/store /opt/app
WORKDIR /opt/app

ENV MIX_APP=store
ENV MIX_ENV=prod
ENV PORT=4000
ENV REPLACE_OS_VARS=true
ENV SHELL=/bin/bash
ENV HOME=/opt/app

EXPOSE 80

ENTRYPOINT ["/opt/app/bin/store"]
CMD ["start"]
