import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :store, Elementary.StoreWeb.Endpoint,
  url: [scheme: "https", port: 443],
  http: [port: 4000, transport_options: [socket_opts: [:inet6]]],
  cache_static_manifest: "priv/static/cache_manifest.json",
  gzip: true

# Do not print debug messages in production
config :logger, level: :info

config :libcluster,
  topologies: [
    production: [
      strategy: Elixir.Cluster.Strategy.Kubernetes.DNS,
      config: [
        service: "store-internal",
        application_name: "store",
        polling_interval: 10_000
      ]
    ]
  ]

config :store, Printful.Api, enable_purchasing: true

config :store, Elementary.Store.Mailer, adapter: Bamboo.MailgunAdapter
